# CREATE AN ALPACA ACCOUNT AND REQUEST API KEYS

API_KEY = 'PKYW2KU4ERSLVK37S28O'
SECRET_KEY = 'hQSNiGEWEnCIiBdzS8LUqM6qwYSuFN2xSMq6Opvo'

'''
ALPACA_URL = 'https://paper-api.alpaca.markets'

HEADERS - {
     'PKO7GYZF6OFKIVYAEHP1': API_KEY,
     'NggY7LkPIM4mAHvn4YqbpF2rAF7IwxQc0tzuOQlH': SECRET_KEY
}
'''